name: gencost
channels:
  - conda-forge
dependencies:
  # Packages required for setting up the environment
  - pip>=21,<25
  - python>=3.10,<3.13

  # Jupyter packages:
  - jupyter
  - nbconvert>=6,<7 # Used to clear notebook outputs in pre-commit hooks

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./[dev,doc]
