[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "rmi.gencost"
description = "A tool for estimating generator unit costs from public utility data."
license = {file = "LICENSE.txt"}
readme = "README.rst"
dynamic = ["version"]
classifiers = [
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.10,<3.12"
dependencies = [
    "bottleneck >= 1.3,< 1.3.8",
    "numexpr >= 2.8, < 2.8.8",
    "numpy >= 1.18.5,<2",
    "networkx >= 3.0,< 3.3",
    "pandas >= 1.4,< 1.6",
    "pandera >= 0.12, < 0.18",
    "platformdirs >=2.6,<4.1",
    "plotly>5.10,<5.19",
    "pyarrow>=7, <15",
    "polars[connectorx]>=0.16,<0.20",
    "rmi.etoolbox @ git+https://github.com/rmi/etoolbox.git",
    "scikit-learn>1.1, <1.4",
    "tqdm >= 4.63,< 4.67",
]

[project.optional-dependencies]
dev = [
    "black[jupyter] >= 22,< 24",
    "coverage>=5.3,<7.4",  # Lets us track what code is being tested
    "pre-commit>=2.9,<3.6",
    "pytest>=7.2.1,<7.5",  # test framework
    "pytest-console-scripts>=1.1,<1.5",  # Allow automatic testing of scripts
    "pytest-cov>=4.0,<4.2",  # Pytest plugin for working with coverage
    "ruff>0.0.259,<0.1.6",
    "tox>=4.2,<4.12",
]
doc = [
    "doc8>=0.9,<1.2",  # Ensures clean documentation formatting
    "furo>=2022.4.7",  # A clean customisable Sphinx documentation theme.
    "rstcheck[sphinx,toml]>=6.1,<6.3",  # ReStructuredText linter
    "sphinx>=4.1,<7.2.7",
    "sphinx-autoapi>=2.0,<3.1",
    "sphinx-issues>=3.0,<3.1",
    "sphinx-autodoc-typehints>1.21,<1.26.0",
    "sphinxcontrib-mermaid>0.7,<0.10.0",
]
tests = []

[project.scripts]  # entry points
gencost-setup = "gencost.data_setup:main"
gencost = "gencost.main:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
gencost = ["*.csv", "*.gzip"]

[tool.setuptools.dynamic]
version = {attr = "gencost._version.__version__"}

[tool.setuptools_scm]
write_to = "src/gencost/_version.py"

#######################################################################################
# Configurations for linters and other tools
#######################################################################################
[tool.black]
line-length = 88
target-version = ["py39", "py310", "py311"]
include = "\\.pyi?$"

[tool.doc8]
max-line-length = 88
ignore-path = "docs/_build"

[tool.pytest.ini_options]
testpaths = ["."]
addopts = ["--verbose"]
log_format = "%(asctime)s [%(levelname)8s] %(name)s:%(lineno)s %(message)s"
log_date_format=" %Y-%m-%d %H:%M:%S"
log_cli = true
log_cli_level = "INFO"
doctest_optionflags = ["NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL", "ELLIPSIS"]
filterwarnings = [
    "ignore:distutils Version classes are deprecated:DeprecationWarning",
    "ignore:Creating a LegacyVersion:DeprecationWarning:pkg_resources[.*]",
]

[tool.rstcheck]
report_level = "WARNING"
ignore_roles = ["pr", "issue", "user", "include"]
ignore_messages = '(Hyperlink target .* is not referenced\.$|Duplicate implicit target name:|An `AttributeError` error occured.*)'
ignore_directives = ["bibliography", "todo", "include"]

[tool.ruff]
select = [
    "A", # flake8-builtins
    "B", # flake8-bugbear
    "C",
    "C4", # flake8-comprehensions
    "E",  # pycodestyle
    "F",  # Pyflakes
    "I", # isort
    "TID", # flake8-tidy-imports
    "N", # pep8-naming
    "PT", # flake8-pytest-style
    "PGH", # pygrep-hooks
    "S", # bandit
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
    "UP", # pyupgrade
    "W",  # pycodestyle
]
ignore = [
    "E501",
    # conflict with ruff format
    "W191",  # tab-indentation
    "E111",  # indentation-with-invalid-multiple
    "E114",  # indentation-with-invalid-multiple-comment
    "E117",  # over-indented
    "D206",  # indent-with-spaces
    "D300",  # triple-single-quotes
    "Q000",  # bad-quotes-inline-string
    "Q001",  # bad-quotes-multiline-string
    "Q002",  # bad-quotes-docstring
    "Q003",  # avoidable-escaped-quote
    "COM812",  # missing-trailing-comma
    "COM819",  # prohibited-trailing-comma
    "ISC001",  # single-line-implicit-string-concatenation
    "ISC002",  # multi-line-implicit-string-concatenation
]
# Allow autofix for all enabled rules (when `--fix`) is provided.
unfixable = ["ISC"]
# By default, always enumerate fixed violations.
show-fixes = true
line-length = 88

[tool.ruff.isort]
known-first-party = ["gencost"]

[tool.ruff.pycodestyle]
max-doc-length = 88

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.flake8-type-checking]
strict = true

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"docs/conf.py" = ["E501"]
"tests/*.py" = ["S101"]
"main.py" = ["S603", "S607"]

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 15
