[build-system]
requires = ["setuptools<66", "setuptools_scm[toml]>=3.5.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rmi.gencost"
description = "A tool for estimating generator unit costs from public utility data."
license = {file = "LICENSE.txt"}
readme = "README.rst"
dynamic = ["version"]
classifiers = [
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
]
requires-python = ">=3.10,<3.12"
dependencies = [
    "bottleneck >= 1.3,< 1.3.8",
    "numexpr >= 2.8, < 2.8.5",
    "numpy >= 1.18.5,<2",
    "networkx >= 3.0,<3.2",
    "pandas >= 1.4,< 2.1",
    "pandera >= 0.12, <0.15",
    "platformdirs >=2.6,<3.3",
    "plotly>5.10,<5.15",
    "pyarrow>=7, <12",
    "rmi.etoolbox @ git+https://github.com/rmi/etoolbox.git",
    "tqdm >= 4.63,< 4.66",
]

[project.optional-dependencies]
dev = [
    "black[jupyter] >= 22,< 24",
    "coverage>=5.3,<7.3",  # Lets us track what code is being tested
    "pre-commit>=2.9,<3.3",
    "pytest>=7.2.1,<7.4",  # test framework
    "pytest-console-scripts>=1.1,<1.4",  # Allow automatic testing of scripts
    "pytest-cov>=4.0,<4.1",  # Pytest plugin for working with coverage
    "ruff>0.0.259,<0.0.263",
    "tox>=4.2,<4.5",
]
doc = [
    "doc8>=0.9,<1.2",  # Ensures clean documentation formatting
    "furo>=2022.4.7",  # A clean customisable Sphinx documentation theme.
    "rstcheck[sphinx,toml]>=6.1,<6.2",  # ReStructuredText linter
    "sphinx>=4.1,<6.2.1",
    "sphinx-autoapi>=2.0,<2.2",
    "sphinx-issues>=3.0,<3.1",
    "sphinx-autodoc-typehints>1.21,<1.24.0",
    "sphinxcontrib-mermaid>0.7,<0.9.0",
]
tests = []

[project.scripts]  # entry points
gencost-setup = "gencost.data_setup:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
gencost = ["*.csv", "*.gzip"]

[tool.setuptools.dynamic]
version = {attr = "gencost._version.__version__"}

[tool.setuptools_scm]
write_to = "src/gencost/_version.py"

#######################################################################################
# Configurations for linters and other tools
#######################################################################################
[tool.black]
line-length = 88
target-version = ["py39", "py310", "py311"]
include = "\\.pyi?$"

[tool.doc8]
max-line-length = 88
ignore-path = "docs/_build"

[tool.isort]
profile = "black"
known_first_party = ["gencost"]

[tool.pytest.ini_options]
testpaths = ["."]
addopts = ["--verbose"]
log_format = "%(asctime)s [%(levelname)8s] %(name)s:%(lineno)s %(message)s"
log_date_format=" %Y-%m-%d %H:%M:%S"
log_cli = true
log_cli_level = "INFO"
doctest_optionflags = ["NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL", "ELLIPSIS"]
filterwarnings = [
    "ignore:distutils Version classes are deprecated:DeprecationWarning",
    "ignore:Creating a LegacyVersion:DeprecationWarning:pkg_resources[.*]",
]

[tool.rstcheck]
report_level = "WARNING"
ignore_roles = ["pr", "issue", "user", "include"]
ignore_messages = '(Hyperlink target .* is not referenced\.$|Duplicate implicit target name:|An `AttributeError` error occured.*)'
ignore_directives = ["bibliography", "todo", "include"]

[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["A", "B", "C", "E", "F", "N", "S", "SIM", "TCH", "W"]
ignore = []
# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F",]
unfixable = []
# By default, always enumerate fixed violations.
show-fixes = true
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
# Same as Black.
line-length = 88
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# Assume Python 3.10.
target-version = "py310"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"docs/conf.py" = ["E501"]
"tests/*.py" = ["S101"]

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 15
