# flake8: noqa

# create a table that maps raw plant_type values to cleaned up labels
# uses material from:
# https://github.com/catalyst-cooperative/pudl/blob/6ea776ede9fd5cdcd09a414a39bf5899e9ab9e3a/src/pudl/transform/params/ferc1.py#L1085

import pandas as pd

steam_list = [
    "*resp. share steam",
    "(6) milwaukee county is a steam utility plant",
    "(steam)",
    "40% share steam",
    "40% share steamsteam (2)",
    "coal",
    "coal fired steam tur",
    "coal fired steam turbine",
    "coal-fired steam",
    "mpc 50% share steam",
    "mpc 50% shares steam",
    "mpc 50%share steam",
    "mpc40%share steam",
    "mpc50% share steam",
    "mpc50% share steam",
    "oil-fired steam",
    "other-steam expenses:",
    "resp share st note 3",
    "resp share st note3",
    "resp share stm note3",
    "resp share stm note3",
    "resp. share steam",
    "respondent's sh-st",
    "respondent's sh.-st.",
    "steam",
    "steam (1)",
    "steam (1) & (2)",
    "steam (2)",
    "steam (3)",
    "steam (4)",
    "steam (5)",
    "steam (6)",
    "steam (7)",
    "steam (8)",
    "steam (a)",
    "steam (a,b)",
    "steam (incl i.c.)",
    "steam (leased)",
    "steam (note 1)",
    "steam (retired)",
    "steam (see note 1)",
    "steam (see note 1,",
    "steam (see note 3)",
    "steam (see notes)",
    "steam - 100%",
    "steam - 64%",
    "steam - 72%",
    "steam 1",
    "steam 100",
    "steam 4, 5",
    "steam a",
    "steam conventional",
    "steam fossil",
    "steam heating plant",
    "steam plant",
    "steam plants",
    "steam retired 2013",
    "steam turbine",
    "steam units 1 2 3",
    "steam units 1 2 3",
    "steam units 1 and 2",
    "steam units 1, 2, 3",
    "steam units 1,2,3",
    "steam units 3 and 4",
    "steam units 4 & 6",
    "steam units 4 5",
    "steam units 4&5",
    "steam units 4&6",
    "steam units 4, 5",
    "steam- 64%",
    "steam- 72%",
    "steam-100%",
    "steam-64%",
    "steam-common production",
    "steam-common production plant",
    "steam-internal comb",
    "steam/fossil",
    "steam;retired - 2013",
    "steam:",
    "steams",
    "stean",
    "stream",
    "unit total steam",
    "unit total-steam",
    "respondent's sh.-st.",
    "respondent's sh-st",
    "40% share steam",
    "resp share stm note3",
    "mpc50% share steam",
    "resp share st note 3",
    "coal fired steam tur",
    "coal fired steam turbine",
    "steam- 64%",
    "steam/fuel oil",
]
combustion_turbine_list = [
    "* gas turbine",
    "*gas turbine",
    "*gas turbine(note 3)",
    "*gas turbine(note3)",
    "add to gas turbine",
    "b-combustion turbine unit",
    "com turbine peaking",
    "comb turb peak units",
    "comb turb peaking",
    "comb turbine peaking",
    "comb. turb-gas oper",
    "comb. turb-gas oper.",
    "comb. turb.",
    "comb. turb. oil oper",
    "comb. turbine (a)",
    "comb. turine",
    "comb.turb-gas oper.",
    "comb.turb.gas/oil op",
    "comb.turb.oil oper",
    "comb.turb.oil oper.",
    "comb.turb.peak.units",
    "combusion turbine",
    "combusition turbine",
    "combustine turbine",
    "combustine turbine",
    "combustion and gas",
    "combustion burbine",
    "combustion tubine",
    "combustion turbin",
    "combustion turbine",
    "combustion turbine",
    "combustion turbine",
    "combustion_turbine",
    "combustionturbine",
    "combution turbin",
    "combution turbine",
    "combutsion turbine",
    "comubstion turbine",
    "conbustion turbine",
    "cumbustion turbine",
    "gas - turbine",
    "gas expander turbine",
    "gas plant",
    "gas trubine",
    "gas turb",
    "gas turb(see notes)",
    "gas turb, diesel",
    "gas turb, int. comb",
    "gas turb, int. comb.",
    "gas turb. (see note",
    "gas turb.(see note5)",
    "gas turb.(see notes)",
    "gas turbin (leasd)",
    "gas turbin (lease",
    "gas turbine",
    "gas turbine",
    "gas turbine",
    "gas turbine # 1",
    "gas turbine #1",
    "gas turbine (2)",
    "gas turbine (a)",
    "gas turbine (leasd)",
    "gas turbine (lease",
    "gas turbine (lease)",
    "gas turbine (leased",
    "gas turbine (leased)",
    "gas turbine (note 1)",
    "gas turbine (note 3)",
    "gas turbine (note1)",
    "gas turbine (see nos",
    "gas turbine - note 1",
    "gas turbine note 3,6",
    "gas turbine note 4,6",
    "gas turbine peaker",
    "gas turbine peaking",
    "gas turbine peakload",
    "gas turbine plant",
    "gas turbine plants",
    "gas turbine-simple",
    "gas turbine-unit 2",
    "gas turbine/int comb",
    "gas turbine/int. cm",
    "gas turbine/intcomb",
    "gas turbine:",
    "gas turbine; retired",
    "gas turbines",
    "gas turbines:",
    "gas turbinint comb",
    "gas turbne/int comb",
    "gas-turbine",
    "gasturbine",
    "gt",
    "gtg/gas",
    "i.c.e. /gas turbine",
    "i.c.e./gas tubine",
    "i.c.e./gas turbine",
    "i.c.e/ gas turbine",
    "i.c.e/gas turbine",
    "jet",
    "jet engine",
    "jet powered turbine",
    "jet turbine",
    "resp share gas note3",
    "simple cycle",
    "simple cycle",
    "simple cycle turbine",
    "gas turbine; retired",
    "gas turbine/fuel oil",
]

combined_cycle_list = [
    "Combined cycle",
    "cc",
    "cc / gas turb",
    "com cycle gas turb",
    "com. cyc",
    "com. cycle",
    "comb cyc",
    "comb cyc (a) (b)",
    "comb cycle",
    "comb cycle (a,b)",
    "comb cycle gas turb",
    "comb cycle/steam tur",
    "comb. cycle",
    "comb. cycle gas turb",
    "combine cycle",
    "combine cycle oper",
    "combined",
    "combined cycle",
    "combined cycle",
    "combined cycle (a,b)",
    "combined cycle - 40%",
    "combined cycle ctg",
    "combined cycle oper",
    "combined cycle opern",
    "combined cycle plant:",
    "combined turbine",
    "combined_cycle",
    "combinedcycle",
    "ctg steam gas",
    "ctg/steam -gas",
    "ctg/steam-gas",
    "gas & steam turbine",
    "gas / steam",
    "gas fired cc turbine",
    "gas steam",
    "gas trb & heat rec",
    "gas tur & comb cyc",
    "gas tur & comb cycl",
    "gas turb-combined cy",
    "gas turb-combined cy",
    "gas turb. & heat rec",
    "gas turb/comb cycle",
    "gas turb/comb. cyc",
    "gas turb/cumb. cyc",
    "gas turb/cumbus cycl",
    "gas turbine / steam",
    "gas turbine-combined cycle",
    "gas turbine/ steam",
    "gas turbine/steam",
    "gas/steam",
    "gas/steam comb cycle",
    "gas/steam comb. cycl",
    "gasturb/comb cycle",
    "igcc",
    "igcc/gas turbine",
    "ngcc",
    "st/gas turb comb cyc",
    "steam & cc",
    "steam & comb cycle",
    "steam & combined ce",
    "steam & gas turbine",
    "steam (comb. cycle)",
    "steam (comb. cycle)gas turbine/steam",
    "steam and cc",
    "steam cc",
    "steam comb cycle",
    "steam/gas turb.",
    "steam/gas turbine",
]
nuclear_list = [
    "nuclear",
    "nuclear (3)",
    "steam(nuclear)",
    "nuclear(see note4)",
    "nuclear steam",
    "nuclear turbine",
    "nuclear - steam",
    "nuclear (a)(b)(c)",
    "nuclear (b)(c)",
    "* nuclear",
    "nuclear (b) (c)",
    "nuclear (see notes)",
    "steam (nuclear)",
    "* nuclear (note 2)",
    "nuclear (note 2)",
    "nuclear (see note 2)",
    "nuclear(see note4)",
    "nuclear steam",
    "nuclear(see notes)",
    "nuclear-steam",
    "nuclear (see note 3)",
]
geothermal_list = ["steam - geothermal", "steam_geothermal", "geothermal"]
internal_combustion_list = [
    "*int combustion (1)",
    "*int. combustion (1)",
    "*internal combust'n",
    "auke bay internal combustion",
    "auke bay internal combustion:",
    "available for specific diesel unit.",
    "available for specific diesel units.",
    "a-internal combustion unit",
    "black start diesel units",
    "black start diesel units:",
    "comb. cyc",
    "comb. turbine",
    "combustion",
    "conemaugh - internal combustion",
    "diesal",
    "diesel",
    "diesel engine",
    "diesel generators",
    "diesel plant",
    "diesel plants",
    "diesel plants:",
    "diesel:",
    "diesel turbine",
    "east hampton diesel",
    "gold creek internal combustion:",
    "ic",
    "int combust (note 1)",
    "int combust (note1)",
    "int combust - note 1",
    "int. combust (note1)",
    "int. combust - note1",
    "int. combustine",
    "int. combustion",
    "int. combustion (1)",
    "int.combustine",
    "interal",
    "internal conbustion",
    "interal combustion:",
    "internal combustion:",
    "internal",
    "internal comb",
    "internal comb recip",
    "internal comb.",
    "internal comb.",
    "internal combust.",
    "internal combustion",
    "internal combustion :",
    "internal combustion auxiliary",
    "internal combustion peaking units",
    "internal combustion plants:",
    "internal combustion reciprocating",
    "internal combustion-diesel",
    "internal combustion:",
    "internal combustion: (emergency standby",
    "internal conbustion:",
    "internal_combustion",
    "international combustion",
    "internl combustion",
    "internl combustion",
    "lemon creek internal combustion",
    "lemon creek internal combustion:",
    "montauk diesel",
    "other / internal combustion :",
    "other/internal combustion",
    "reciprocating engine",
    "shawville - internal combustion",
    "steam internal comb",
]
wind_list = [
    "(7) montfort wind farm was purchased dec. 2012.",
    "rosiere wind turbines",
    "suisun wind power plant (r)",
    "(7) montfort wind farm was purchased dec. 2012.",
    "wind",
    "wind energy",
    "wind turbine",
    "wind - turbine",
    "wind generation",
    "wind turbin",
    "wind turbine plant",
    "wind turbine plants",
    "wind turbine plants:",
    "wind turbine:",
    "wind turbines",
    "wind:",
]
photovoltaic_list = [
    "community solar gardens",
    "other production - solar",
    "photovoltaic",
    "sixth street solar",
    "solar",
    "solar array",
    "solar electric",
    "solar photovoltaic",
    "solar photovoltiac",
    "solar plant",
    "solar plants",
    "solar plants:",
    "solar project",
    "solar:",
    "proj dvlpmnt div solar photovoltaic project:",
    "photo voltaic generating plants:",
]
solar_thermal_list = ["solar thermal", "solar_thermal"]
fuel_cell_list = ["fuel cell", "fuel_cell", "fuel cell:"]
hydro_list = [
    "(1) the dixon hydro electric generating facility",
    "(6) excludes portion allocated to other water",
    "(hydroelectric facility)",
    "a - hydro license project no. 2315.",
    "a-hydro license project no. 2315",
    "additional hydro plant",
    "all other hydro misc. plant, resv., etc.",
    "all other hydro miscellaneous plant",
    "all other hydro plant, resv., misc., etc.",
    "conventional hydro",
    "hydraulic",
    "hydraulic (1):",
    "hydraulic race (project no. 2424)(note 1)",
    "hydraulic:",
    "hydro",
    "hydro -",
    "hydro : licensed proj. no.",
    "hydro electric",
    "hydro lic project no.",
    "hydro lic. project no.",
    "hydro license",
    "hydro license no.",
    "hydro plant:",
    "hydro plants",
    "hydro plants:",
    "hydro plants: licensed proj no.",
    "hydro plants: licensed proj. no.",
    "hydro-electric",
    "hydro-neal shoals",
    "hydro:",
    "hydro: lic project no.",
    "hydro: lic. project no.",
    "hydro: license no.",
    "hydroelectric",
    "hydroelectric : licensed proj. no.",
    "hydroelectric generating plants",
    "hydroelectric generating plants :",
    "hydroelectric generating plants:",
    "hydroelectric: licensed proj. no.",
    "hyrdo",
    "neal shoals-hydro license",
    "other hydro assets (resvr., strm gages, etc.)",
    "other hydro assets (resvr.,strm gages, etc.)",
    "other hydro costs:",
    "research and development costs (hydros)",
    "small hydroelectric generating plants:",
    "small hydroelectric plants:",
    "talcville hydro station(project no. 4402)(note 1",
    "the hydro plant above",
    "unallocated - hydros",
    "unallocated hydros",
]
storage_list = [
    "daily storage",
    "storage",
    "storage (re-reg)",
    "storage - dailey",
    "storage - daily",
    "storage - weekly",
    "storage reservoir",
    "weekly storage",
]
na_category_list = [
    "",
    "(left blank)",
    "(see note 5)",
    "(see note 7)",
    "--",
    "0",
    "0.0000",
    "combined heat/power",
    "common",
    "common expenses",
    "conventional",
    "expenses commom to",
    "expenses common to",
    "footnote",
    "fuel facilities",
    "fuel oil",
    "gas",
    "n/a",
    "na",
    "na_category",
    "non-applicable",
    "none",
    "none.",
    "not applicable",
    "not applicable.",
    "not in service",
    "not in service in",
    "oil",
    "other",
    "other generation",
    "other generation plt",
    "package",
    "peach bottom",
    "plant retired- 2013",
    "plants sold in 1999",
    "resp share (note 11)",
    "resp share - note 11",
    "resp share - note 5",
    "resp. share (note 2)",
    "resp. share (note 3)",
    "resp. share (note 4)",
    "resp. share (note 6)",
    "resp. share (note 8)",
    "resp. share (note 9)",
    "resp. share (note11)",
    "resp. share (note2)",
    "resp. share (note4)",
    "resp. share (note6)",
    "resp. share (note8)",
    "resp. share - note 2",
    "resp. share - note 4",
    "resp. share - note 6",
    "resp. share - note 7",
    "resp. share - note 8",
    "resp. share - note 9",
    "resp. share note 11",
    "respondent's share",
    "retired",
    "retired - 2013",
    "retired in 1978",
    "retired in 1981",
    "see pgs 402.1-402.3",
    "see pgs 403.1-403.9",
    "sold april 16, 1999",
    "sold may 07, 1999",
    "storage/pipelines",
    "unit total (note 2)",
    "unit total (note 3)",
    "unit total (note2)",
    "unit total (note3)",
    "waste heat",
    "—",
]
"""A mapping from canonical plant kinds (keys) to the associated freeform strings
(values) identified as being associated with that kind of plant in the FERC Form 1 raw
data.

There are many strings that weren't categorized, Solar and Solar Project were not
classified as these do not indicate if they are solar thermal or photovoltaic. Variants
on Steam (e.g. "steam 72" and "steam and gas") were classified based on additional
research of the plants on the Internet.
"""

# print(plant_type_categories)
plant_type_dict = {}

# combined_cycle_list
for x in combined_cycle_list:
    plant_type_dict[x] = "combined cycle"

# combustion_turbine_list
for x in combustion_turbine_list:
    plant_type_dict[x] = "combustion turbine"

# fuel_cell_list
for x in fuel_cell_list:
    plant_type_dict[x] = "fuel cell"

# geothermal_list
for x in geothermal_list:
    plant_type_dict[x] = "geothermal"

# hydro_list
for x in hydro_list:
    plant_type_dict[x] = "hydro"

# internal_combustion_list
for x in internal_combustion_list:
    plant_type_dict[x] = "internal combustion"

# na_category_list
for x in na_category_list:
    plant_type_dict[x] = "na category"

# nuclear_list
for x in nuclear_list:
    plant_type_dict[x] = "nuclear"

# photovoltaic_list
for x in photovoltaic_list:
    plant_type_dict[x] = "photovoltaic"

# solar_thermal_list
for x in solar_thermal_list:
    plant_type_dict[x] = "solar thermal"

# steam_list
for x in steam_list:
    plant_type_dict[x] = "steam"

# storage_list
for x in storage_list:
    plant_type_dict[x] = "storage"

# wind_list
for x in wind_list:
    plant_type_dict[x] = "wind"

PlantTypes = pd.DataFrame.from_dict(plant_type_dict, orient="index")
PlantTypes["key"] = PlantTypes.index
PlantTypes.columns = ["value", "key"]
PlantTypes.to_csv("plant_types.csv", index=False)
