"""

Objective: merge vom, fom, and som output 
(generated by running r code) from andrew into epd

pre-work: run r scripts in temp_output folder

"""

import warnings
import pandas as pd
import numpy as np
from gencost.crosswalk import Crosswalk
from gencost.waterfall import DataBySubplant
from platformdirs import user_cache_path, user_documents_path
from gencost.package_data import PACKAGE_PATH


xwalk = Crosswalk()
# self to be able to copy / paste from waterfall.py for dev ease
self = DataBySubplant(xwalk)


def get_epd_w_vom_fom_som():
    return self.get_eternally_present_by_generator().merge(
        vom_fom_som=pd.read_csv(PACKAGE_PATH / "results_new_data.csv").assign(
            report_date=lambda x: pd.to_datetime(x["report_date"], format="%Y-%m-%d")
            + pd.DateOffset(days=1)
        ),
        on=["plant_id_eia", "generator_id", "report_date", "prime_mover"],
        how="left",
        indicator=True,
    )
